const hangmanWords = [
    { word: "elephant", hint: "Large land animal with a trunk" },
    { word: "guitar", hint: "Musical instrument with strings" },
    { word: "astronaut", hint: "Person who travels to space" },
    { word: "mountain", hint: "High natural elevation on Earth" },
    { word: "rainbow", hint: "Colorful arc seen after rain" },
    { word: "butterfly", hint: "Insect with colorful wings" },
    { word: "chocolate", hint: "Sweet treat made from cocoa" },
    { word: "volcano", hint: "Mountain that can erupt lava" },
    { word: "kangaroo", hint: "Australian animal that hops" },
    { word: "pyramid", hint: "Ancient triangular structures in Egypt" },
    { word: "airplane", hint: "Flying vehicle" },
    { word: "basketball", hint: "Sport with a hoop and ball" },
    { word: "penguin", hint: "Bird that cannot fly but swims" },
    { word: "umbrella", hint: "Used for protection against rain" },
    { word: "computer", hint: "Device used for computing and internet" },
    { word: "dinosaur", hint: "Extinct reptile from prehistoric times" },
    { word: "scissors", hint: "Tool used to cut paper" },
    { word: "microscope", hint: "Device to see very small objects" },
    { word: "library", hint: "Place with many books" },
    { word: "telescope", hint: "Device to see far away objects in space" },
    { word: "submarine", hint: "Underwater vessel" },
    { word: "sunglasses", hint: "Protects eyes from bright light" },
    { word: "telephone", hint: "Device used for calling someone" },
    { word: "helicopter", hint: "Aircraft with rotating blades" },
    { word: "octopus", hint: "Sea creature with eight arms" },
    { word: "piano", hint: "Large musical instrument with keys" },
    { word: "camera", hint: "Used to capture photographs" },
    { word: "backpack", hint: "Bag used to carry items on your back" },
    { word: "notebook", hint: "Used to write notes" },
    { word: "lighthouse", hint: "Tall structure guiding ships" },
    { word: "pizza", hint: "Popular Italian dish with cheese" },
    { word: "skateboard", hint: "Board with wheels ridden for fun" },
    { word: "island", hint: "Land surrounded by water" },
    { word: "rocket", hint: "Vehicle used to travel to space" },
    { word: "honey", hint: "Sweet substance made by bees" },
    { word: "cactus", hint: "Spiky plant found in deserts" },
    { word: "treasure", hint: "Valuable objects hidden or lost" },
    { word: "glacier", hint: "Large slow-moving ice mass" },
    { word: "fireworks", hint: "Explosive lights in the sky for celebrations" },
    { word: "jellyfish", hint: "Sea creature with a gelatinous body" },
    { word: "drum", hint: "Musical instrument that is hit" },
    { word: "pirate", hint: "Person who robs ships at sea" },
    { word: "strawberry", hint: "Red fruit with seeds on the outside" },
    { word: "whale", hint: "Large sea mammal" },
    { word: "avalanche", hint: "Snowfall sliding down a mountain" },
    { word: "robot", hint: "Mechanical machine programmed to do tasks" },
    { word: "zebra", hint: "African animal with black-and-white stripes" },
    { word: "volleyball", hint: "Sport played with a ball over a net" },
    { word: "diamond", hint: "Precious gem often used in jewelry" }
];
